messages:
    nopermission: "&4You don't have permission to do this"
    availablearenas: "&6Available arenas:&r "
	arenadisabled: "&6Arena is disabled"
	arenarunning: "&6Arena already running"
	arenadisabling: "&6Arena is disabling"
    playerscountinarena: "&6Current number of players in arena: {COUNT}"
	limitreached: "&6Slot limit reached."
	playerjoinedtoplayer: "&6You joined the arena %s."
	playerjoinedtoothers: "&6Player %s joined the arena"
	playerlefttoplayer: "&6You left the arena"
	playerlefttoothers: "&6Player {PLAYER} left the game"
	playervotedforstart: "&6You voted for game start"
	playeralreadyvotedforstart: "&6You already voted"
	arenastarted: "&6Arena started. Time limit is {TIMELIMIT} seconds"
	arenacountdown: "&6Arena starts in {COUNTDOWN} seconds"
	arenatimeout: "&6Time is out."
	playerwontoplayer: "&6You won the game"
	playerlosttoplayer: "&6You lost the game"
	playerlosttoothers: "&6Player {PLAYER} lost the game"
	playerwonbroadcast: "&9[TNTRun] &a{PLAYER}&r won the game on arena &c{ARENA}"
	playerrewardmessage: "&6You have been rewarded: {REWARD}"
	p2_saved: "p2 saved"
	arena_not_found: "&4Arena %s does not exist."
	disable_arena_first: "&4Disable arena %s first."